APACHE_JAVA_PROJECTS = [
    # ".NET Ant Library",
    # "Abdera",
    # "Accumulo",
    # "ACE",
    # "ActiveMQ",
    # "Airavata",
    # "Ambari",
    # "Anakia",
    # "Ant",
    # "AntUnit",
    # "Any23",
    # "Apex",
    # "Archiva",
    # "Aries",
    # "Avro",
    # "Axiom",
    # "Axis2",
    # "Beam",
    # "Beehive",
    # "Bigtop",
    # "BookKeeper",
    # "Brooklyn",
    # "BVal",
    # "Calcite",
    # "Camel",
    # "CarbonData",
    # "Cassandra",
    # "Cayenne",
    # "Chainsaw",
    # "Chemistry",
    # "Chukwa",
    # "Clerezza",
    # "Click",
    # "CloudStack",
    # "Cocoon",

    # the above needs to run again without the spreadsheet creation


    # "Commons BCEL",
    # "Commons BeanUtils",
    # "Commons BSF",
    # "Commons Chain",
    # "Commons CLI",
    # "Commons Codec",
    # "Commons Collections",
    # "Commons Compress",
    # "Commons Configuration",
    # "Commons Daemon",
    # "Commons DBCP",
    # "Commons DbUtils",
    # "Commons Digester",
    # "Commons Discovery",
    # "Commons EL",
    # "Commons Email",
    # "Commons Exec",
    # "Commons FileUpload",
    # "Commons Functor",
    # "Commons HttpClient",
    # "Commons IO",
    # "Commons JCI",
    # "Commons JCS",
    # "Commons Jelly",
    # "Commons JEXL",
    # "Commons JXPath",
    # "Commons Lang",
    # "Commons Launcher",
    # "Commons Logging",
    # "Commons Math",
    # "Commons Modeler",
    # "Commons Net",
    # "Commons OGNL",
    # "Commons Pool",
    # "Commons Proxy",
    # "Commons RNG",
    # "Commons SCXML",
    # "Commons Validator",
    # "Commons VFS",
    # "Commons Weaver",
    # "Compress Ant Library",
    # "Continuum",
    # "Cordova",
    # "Crunch",
    # "cTAKES",
    # "Curator",
    # "CXF",
    # "Daffodil",
    # "DataFu",
    # "DeltaSpike",
    # "Derby",
    # "DeviceMap",
    # "DirectMemory",
    # "Directory",
    # "Directory Server",
    # "Directory Studio",
    # "Drill",


    # "ECS",
    # "Edgent",
    # "Empire - db",
    # "Etch",
    # "Excalibur",
    # "Falcon",
    # "Felix",
    # "Flink",
    # "Flume",
    # "Fluo",
    # "Fluo Recipes",
    # "Fluo YARN",
    # "FOP",
    # "Forrest",
    # "Fortress",
    # "FreeMarker",
    # "FtpServer",
    # "Geronimo",
    # "Giraph",
    # "Gora",
    # "Groovy",
    # "Guacamole",
    # "Hama",
    # "Harmony",


    # "HBase", -- not able to load after running 5 hours only on this project


    # "Helix",
    # "Hive",
    # "Hivemind",
    # "HttpComponents Client",
    # "HttpComponents Core",
    # "Hudi",
    # "Ignite",
    # "Isis",
    # "Ivy",
    # "IvyDE",
    # "Jackrabbit",
    # "Jakarta Cactus",
    # "JAMES",
    # "jclouds",
    # "Jena",
    # "JMeter",
    # "JSPWiki"

    # "Karaf",
    # "Kerby",
    # "Knox",
    # "Lens",
    # "Lenya",
    # "Log4j 2",
    # "Lucene Core"

    # "Mahout",
    # "ManifoldCF",
    # "Marmotta",
    # "Maven"

    # "Maven Doxia",
    # "MetaModel",
    # "MINA",
    # "MRUnit"

    # "MyFaces",
    # "Nutch",
    # "ODE",
    # "OFBiz",
    # "Olingo",
    # "Oltu - Parent"
    # "OODT",
    # "Oozie",
    # "OpenJPA",


    # "OpenMeetings",
    # "OpenNLP",
    # "OpenWebBeans",
    # "ORC",
    # "ORO",

    # "Parquet",
    # "PDFBox",
    # "Phoenix",
    # "Pig",
    # "Pivot",
    # "PLC4X",
    # "POI",
    # "Polygene",
    # "Portals",
    # "Props Ant Library"

    # "Qpid",
    # "Rat",
    # "REEF",
    # "Regexp",
    # "River",
    # "Roller",
    # "Sandesha2",
    # "Santuario",
    # "Scout",
    # "ServiceMix",
    # "Shale",
    # "Shindig",
    # "Shiro",
    # "Sling",


    # "Solr" -- Failed loading
    #
    # "Spark",
    # "Spatial Information System",
    # "Sqoop",
    # "SSHD",
    # "Stanbol"
    #
    # "Storm",
    # "Stratos",
    # "Struts"


    "Synapse",
    "Syncope",
    "Tajo"

    # "Tapestry",
    # "Taverna",
    # "Tentacles",
    # "Texen",
    # "Tez",
    # "Thrift",
    # "Tika",
    # "Tiles",
    # "Tobago",
    # "Tomcat",
    # "TomEE",
    # "Torque",
    # "Turbine",
    # "Tuscany",
    # "UIMA",
    # "Velocity",
    # "Velocity DVSL",
    # "Velocity Tools",
    # "VSS Ant Library",
    # "VXQuery",
    # "Vysper",
    # "Whirr",
    # "Whisker",
    # "Wicket",
    # "Wink",
    # "Woden",
    # "Wookie",
    # "Xalan",
    # "Xerces",
    # "Xindice",
    # "XML Commons External",
    # "XML Commons Resolver",
    # "XML Graphics Commons",
    # "XMLBeans",
    # "Yetus",
    # "Zeppelin",
    # "ZooKeeper"
]
